package.json, yarn.lock
There were some deps in dependencies that should have been in devDependencies, and this adds react and react-native to peerDependencies
=> chore(deps): peerDependencies and organized devDeps

.codecov.yml
Removing codecov from the status checks. The comment it leaves is fine enough for the reviewer to triage.
=> ci(codecov): removes commit status checks

src/create-glamorous.js
**What**: #28 points out that `Tocuhable` components wrapping `glamorous` components result in **native prop** forwarding failures. This is because the `glamorous` components do not implement `setNativeProps`
**Why**: To allow native property forwarding
**How**: `setNativeProps` is added to the `glamorous` component
The following problematic code now works:
```js
<TouchableHighlight>
<glamorous.View />
</TouchableHighlight>
```
Note: this was verified hands-on, and was unable to verify in units due to https://github.com/robinpowered/glamorous-native/issues/32
Closes #28
=> fix(create-glamorous): forward nativeProps to inner component

src/index.js
**What**: Adds camel cased factory functions, previously `glamorous.touchablehighlight`, and now in addition (to avoid breaking changes) `glamorous.touchableHighlight`
**Why**: Expected function naming
**How**: Added as an alias, rather than a replacement, to avoid breaking changes
=> feat(glamorous): add camel case aliases to builtin component factories

package.json, src/react-native-elements.js
**What**: Adds support for versions of React Native dating back to `react-native@0.14.x`
**Why**: Not all users are on the latest version
**How**: Lowers the dependency versions, as well as gracefully including support for newer React Native components only when they exist in the version of the dependent.
This fix has been verified in this test project on `react-native@0.14.x` https://github.com/ajwhite/glamorous-with-legacy-react-native
Closes #25
=> fix(react-native-elements): support earlier versions of react native

package.json
**What**: `peerDependencies` are not being satisfied when they should.
**Why**: Semver treats `0.x` releases with tighter constraints as they are considered pre-releases. React Native is on a `0.x` version, which means our `"peerDepdencies": "^0.14.0"` is not satisfied by other `0.x` releases.
**How**: This now uses `>=` for evaluating `react-native` dependency versions
=> fix(package): use >= instead of caret for 0.x peer deps

src/__tests__/index.test.js, src/__tests__/tiny.test.js, src/create-glamorous.js, src/get-styles.js
**What**: Support for React's `context` in dynamic styles
**Why**: Because you couldn't before!
**How**: `context` is now a third parameter in a dynamic styles function
```js
const View = glamorous.view(
(props, theme, context) => ({ /* style with context */ })
)
```
=> feat(context): add dynamic style context support

src/__tests__/__snapshots__/glamorous.test.js.snap, src/__tests__/glamorous.test.js, src/get-styles.js
**What**: #35 styles-as-properties had lower priority than `style` property
```js
<glamorous.View
style={{backgroundColor: 'green'}}
backgroundColor="blue"
/>
// should have `blue` background
```
**Why**: The styles-as-properties should have the highest priority
**How**: These are now the last styles added to the component's style array
=> fix(getStyles): styles-as-properties priority

src/index.js
**What**: Builtin components are now exported
```js
import {View} from 'glamorous-native'
<View height={300} width={300}>..</View>
```
**Why**: Because it makes life easier 😅 
**How**: Each builtin component is manually exported. In the future, it would be nice to do something a bit more automated, such as in https://github.com/paypal/glamorous/pull/131. Exports have to be known statically, so they can't be dynamically generated.
=> feat(glamorous): export builtin components

src/__tests__/__snapshots__/glamorous.test.js.snap, src/__tests__/__snapshots__/index.test.js.snap, src/__tests__/index.test.js, src/split-props.js
**What**: Fixes an issue when `style={aNumber}` (from a `StyleSheet` entry). This leads to a problem where built-in components (any component using `propsAreStyleOverrides`), because it expects `props.style` to be an `Object` that it can add to. 
**Why**: Any `propsAreStyleOverrides` props will be ignored when `style={aNumber}`
**How**: Instead of sharing the `props.style` in `splitProps`, we instead maintain an independent object. We actually don't need to use this, because `getStyle` uses it independently from `styleOverrides` already 🙌 
This also explains why there were duplicate styles showing up when `style={anObject}` in conjunction with `propsAreStyleOverrides` -- the style was being added to two objects
=> fix(styles): StyleSheet style blocked styleOverrides

README.md
**What**:
Add note about configuring Jest 
**Why**: 
Since this module doesn't need to be transformed by Babel, we need to tell Jest not to try to transform it.
This fixes errors like `({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createGlamorous from './create-glamorous'`
**How**:
By using my keyboard to add the words to the text editor on my screen. 😅
=> Add note about configuring Jest

package.json, src/__tests__/index.test.js, src/__tests__/with-theme.test.js, src/create-glamorous.js, src/react-compat.js, src/theme-provider.js, src/with-theme.js, yarn.lock
**What**:
Adds `prop-types` module and runs the [`React-PropTypes-to-prop-types` codemod](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types)
**Why**:
This ensures compatibility with React 16+. Fixes `Cannot read property 'object' of undefined` on React 16.0.0-beta.1
**How**:
```bash
$ cd glamorous-native
$ yarn add prop-types
$ cd .. && git clone https://github.com/reactjs/react-codemod.git
$ jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js ../glamorous-native/src`
```
=> Consume PropTypes from the prop-types module

src/__tests__/index.test.js, src/__tests__/theme-provider.test.js, src/__tests__/tiny.test.js, src/get-styles.js
**What**:
Moving theme from second argument to a theme prop. 
**Why**:
To match the glamorous-web api.
**How**:
- Updated tests
- updated `getStyles` til tests passed 😁
Talked with @kentcdodds about this at ReactRally. I will probably make an update to the code-mod so that it can catch the native cases as well. He also mentioned leaving it as a second prop to not break contract. I didn't do that in this case, but could be easily achieved if you want me to go that route let me know.
=> Moved Theme to Props

src/create-glamorous.js
Some of my components are stateless functions, they accept style prop and pass it down to children. I want to style them with glamorous. However, I get annoying yellowbox warnings like this
```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.
Check the render method of `Icon`.
in IconBase (created by Icon)
in Icon (at PhotoPickerItem.js:51)
```
where `IconBase` is stateless function and `Icon` is `glamorous(IconBase, { displayName: 'Icon' })(...)`. If I replace IconBase with class, those warning no longer appear.
So I added this simple condition. Glamorous component factory now checks if wrapped component is stateless function, and if so, it will not give it ref
I tries this with react-native 0.45.1, I did a quick search and I think this …
=> Do not give refs to stateless function components

package.json, typings/built-in-component-factories.d.ts, typings/built-in-glamorous-components.d.ts, typings/component-factory.d.ts, typings/glamorous-component.d.ts, typings/glamorous.d.ts, typings/helpers.d.ts, typings/style-arguments.d.ts
Hey,
I used glamorous-native in a Typescript project and wanted to contribute my declaration files so that other Typescript projects can benefit.
Greetings 
Kalle
=> added typescript declarations

typings/glamorous-component.d.ts, typings/glamorous.d.ts
I removed the interfaces WithComponent and WithProps, because those functions are not available in glamorous-native.
Thanks to @epeli
=> removed unavailable function interfaces

src/split-props.js
For undocumented reasons, importing View in recent versions of RN (RN50/Expo SDK23) does return string "RCTView" in prod, while in dev it returns a function.
It is the only component in RN codebase that behaves this way in prod build.
See for example ReactNativeElementMap log output:
```
17:17:30: ReactNativeElementMap Object {
17:17:30:   "FlatList": [Function FlatList],
17:17:30:   "Image": [Function anonymous],
17:17:30:   "ListView": [Function anonymous],
17:17:30:   "ScrollView": [Function anonymous],
17:17:30:   "SectionList": [Function SectionList],
17:17:30:   "Text": [Function anonymous],
17:17:30:   "TextInput": [Function anonymous],
17:17:30:   "TouchableHighlight": [Function anonymous],
17:17:30:   "TouchableNativeFeedback": [Function anonymous],
17:17:30: …
```
=> Ensure Glamorous forward props to RCTView rootEl

src/react-native-elements.js
- Added `ImageBackground` to the `ReactNativeElementMap` in react-native-elements.js
**What**: - Added `ImageBackground` to the `ReactNativeElementMap` in react-native-elements.js
**Why**: When upgrading react native versions, the Image component can no longer have child components, so ImageBackground should be used instead
**How**: - Added `ImageBackground` to the `ReactNativeElementMap` in react-native-elements.js
=> Added ImageBackground to the supported elements

typings/built-in-component-factories.d.ts, typings/built-in-glamorous-components.d.ts, typings/glamorous.d.ts, typings/helpers.d.ts
**What**:
Support for Typescript 2.9 and latest `@types/react-native`
**Why**:
There where type errors
```
node_modules/glamorous-native/typings/built-in-component-factories.d.ts:5:3 - error TS2724: Module '"/Users/esamatti/code/app/node_modules/@types/react-native/index"' has noexported member 'ScrollViewStyle'. Did you mean 'ScrollViewBase'?
5   ScrollViewStyle,
~~~~~~~~~~~~~~~
node_modules/glamorous-native/typings/built-in-glamorous-components.d.ts:5:3 - error TS2724: Module '"/Users/esamatti/code/app/node_modules/@types/react-native/index"' has no exported member 'ScrollViewStyle'. Did you mean 'ScrollViewBase'?
5   ScrollViewStyle,
~~~~~~~~~~~~~~~
node_modules/glamorous-native/typings/glamorous.d.ts:23:3 - error TS2724: Module …
```
=> Fix typings for TypeScript 2.9 and latest @types/react-native

typings/glamorous.d.ts
Updated typings for rootEl.
Previously this wouldn't compile:
```ts
glamorous(ButtonText, {rootEl: Text})
```
because of Text not extending from Element.
If I'm not mistaken, Element is only used in the web version of React.
=> Update typings for rootEl

src/is-style-prop.js
otherwise the style props are forwarded down to the wrapped Animated.ScrollView
=> Add missing viewStyleComponents
